import { Inicio } from "./Inicio/Inicio";
import { Contactanos } from "./Contáctanos/Contactanos";
import { Productos } from "./Productos/Productos";
import { QuienesSomos } from "./QuienesSomos/QuienesSomos";
import { Imagen } from "./Imagen";
import { PaginaNoEncontrada } from "./404/PaginaNoEncontrada";
import { Titulo } from "./Titulo";
import { Imagenes } from "./Imagenes";
import { Parrafo } from "./Parrafo";
export { Inicio, Contactanos, Productos, QuienesSomos, Imagen, PaginaNoEncontrada, Titulo, Imagenes, Parrafo };
